### ISSUE TITLE
Warning: Undefined array key "classes"

### ISSUE THREAD

**Issue by dvhebesha** [gdarko/digital-license-manager#20]
Hello iam getting this error in my account

Warning: Undefined array key "classes" in /wp-content/plugins/digital-license-manager/templates/woocommerce/dlm/my-account/licenses/partials/table-activations-row-actions.php on line 38

Warning: Undefined array key "disabled" in /wp-content/plugins/digital-license-manager/templates/woocommerce/dlm/my-account/licenses/partials/table-activations-row-actions.php on line 58

![error](https://user-images.githubusercontent.com/121833403/219228455-0366d226-8db9-427d-b6aa-d99399063fc9.PNG)

**Comment by gdarko** [comment]
Hey @dvhebesha ,

The issue has been resolved in v1.4.2

Best Regards,
Darko
