### ISSUE TITLE
Using digital license manager without woo

### ISSUE THREAD

**Issue by josh-tt** [gdarko/digital-license-manager#23]
Hi there, just checking out your plugin. I see it says 'Compatible with WooCommerce for selling licenses but also works without it.' but there seems to be no information as to how to use it without WooCommerce. Is that with the Pro Version and your software manager? Or is that with any cpt, or via the rest api. Any specific place to start digging? Thanks

**Comment by gdarko** [comment]
Hey @josh-tt , 

The plugin does not require WooCommerce to run, however WooCommerce is defacto standard to run the plugin if you want to monetize it. Without WooCommerce it will act like a license database on which you can still use the REST api to activate/deactivate/validate licenses. If you can think of use case without WooCommerce then you can also use it like that.

Best Regards,
Darko

**Comment by josh-tt** [comment]
Thanks Darko, I will dig into it in the coming days. I just need a pool of pre-defined serials and a system that keeps track of what's taken so it sounds like it might be a fit. Your solution seemed to be the cleanest of the bunch that I'd looked at, so I'm looking forward to checking it out.
