### ISSUE TITLE
Auto delivery

### ISSUE THREAD

**Issue by Knightsepehr** [gdarko/digital-license-manager#25]
Hi , i installed and tried the plugin but when i tried it , it does not deliver the license one the automatic mode and i have to use the status mode to deliver the license

**Comment by gdarko** [comment]
Hey @Knightsepehr  

Did you selected delivery status in Settings > WooCommerce > Order status delivery?  If so this should work once the order transitions to that status.

Also, there are some plugin like [Autocomplete Orders](https://wordpress.org/plugins/autocomplete-woocommerce-orders/) that will mark the order as complete after payment or if your products are set to "Virtual" they should be marked as complete right away with most common gateways like Stripe.

Best Regards,
Darko

**Comment by Knightsepehr** [comment]
Thanks for the reply.
I know about the auto complete thing but i wanted to know if this feature is broken or something.
this is the feature im talking about : 
![image](https://user-images.githubusercontent.com/45466228/235983167-f0e211f1-5683-46aa-92d9-01c289334681.png)
