### ISSUE TITLE
API list endpoint does not work anymore

### ISSUE THREAD

**Issue by Beowulf50** [gdarko/digital-license-manager#31]
The list endpoint just returns the following error:
```json
{
    "code": "data_error",
    "message": "No licence keys found for your query.",
    "data": {
        "code": 404
    }
}
```
The API keys are correct and there are license keys.

**Comment by gdarko** [comment]
Hey,

The issue could not be reproduced. So i am guessing something isn't right on your environment.

Best,
Darko

**Comment by Beowulf50** [comment]
> Hey,
> 
> The issue could not be reproduced. So i am guessing something isn't right on your environment.
> 
> Best, Darko

Hi,

This used to work fine before, but now it's not working. See the screenshot below. (There are license keys on the site)
![image](https://github.com/gdarko/digital-license-manager/assets/61357558/b3377a5c-fb9a-47ff-95b8-073b673f313d)

Best regards,

Punisher
