### ISSUE TITLE
Issue with REST API GET /licenses

### ISSUE THREAD

**Issue by PunisherDev** [gdarko/digital-license-manager#32]
The endpoint does not work if you add your consumer key and secret as parameters. 

![image](https://github.com/gdarko/digital-license-manager/assets/61357558/cd6fa99f-62cb-4a1d-a162-cbb552cda702)

Caused by that line of code as it tries to use the parameters for the query.

Also, it responds with no results for your query if you try to use parameters per_page and page, only parameters like order_id work.

Documentation for HTTP basic auth is incorrect
![image](https://github.com/gdarko/digital-license-manager/assets/61357558/15cda9a7-2df5-47c5-af5f-2aab8e7c4a1e)

Header name: Authentication -> Authorization
Header value: Bearer -> Basic

**Comment by gdarko** [comment]
Fixed in 1.5.6
