### ISSUE TITLE
License keys not delivering.

### ISSUE THREAD

**Issue by PunisherDev** [gdarko/digital-license-manager#33]
License key delivery is broken in the latest version. Downgrading to version 1.4.3 fixes it

**Comment by gdarko** [comment]
Hey @Beowulf50 - Thanks for reporting the issue.

1. Do you see any errors in debug.log?
2. Do you use generators or stocked licenses?

Thanks,

Best regards,
Darko

**Comment by Beowulf50** [comment]
> Hey @Beowulf50 - Thanks for reporting the issue.
> 
> 1. Do you see any errors in debug.log?
> 2. Do you use generators or stocked licenses?
> 
> Thanks,
> 
> Best regards, Darko

Hi Darko,

I heard about it from a few friends who use your plugin. The issue started on the first day of this month, when the latest version was released. They use stocked keys.

Best regards,

Beowulf

**Comment by gdarko** [comment]
This issue has been resolved in the latest v1.5.1, @PunisherDev
