### ISSUE TITLE
Dates displayed inconsistently

### ISSUE THREAD

**Issue by pondermatic** [gdarko/digital-license-manager#4]
@gdarko,

## Issue
The expiration date/time is displayed inconsistently, which can be confusing.

## Example

When `wp_dlm_licenses.expires_at` = '2023-08-15 04:00:00.0' and
* `get_option( 'gmt_offset' )` = '-5.0'
* `get_option( 'date_format' )` = 'F j, Y'
* `get_option( 'time_format' )` = 'g:i a'

These pages display:
| Page | Display |
| ---- | ------- |
| License Manager ->  Licenses | August **14**, 2022 |
| License Manager ->  Licenses -> Edit license | 2022-08-15 |
| My account -> Orders -> View | August 15, 2023 |
| My account -> Licenses | August **14**, 2023 |
| My account -> Licenses -> View | August **14**, 2023 |

## Options

1. Always display the date relative to UTC. This is consistent but vague.
    **August 15, 2023**
2. Display the "UTC" timezone abbreviation. Showing the timezone without the time is unusual.
    **August 15, 2023, UTC**
3. Display the local timezone abbreviation. Showing the timezone without the time is unusual.
    **August 15, 2023, CDT**
4. Display the time and the local timezone abbreviation. This is my preferred option.
    **August 15, 2023, 2:00 am CDT**
5. Display the time and the local timezone identifier. This is lengthy but is the clearest because people in other countries may not be familiar with the local timezone abbreviation.
    **August 15, 2023, 2:00 am America/Chicago**

## Proposed Solution 1

* The expiration date must always be shown as `"$date, $time $timezone"`.
* The date format must use the WordPress `'date_format'` option.
* The time format must use the WordPress `'time_format'` option.
* Since WordPress doesn't have a `'timezone_format'` option:
    1. DLM should default to `' T'` and run it through `apply_filter()`, or
    2. add a `'dlm_timezone_format'` option in the "License Manager -> Settings -> General" page with a link to the [WordPress documentation on date and time formatting](https://wordpress.org/support/article/formatting-date-and-time/).

## Proposed Solution 2

An alternative solution is to add a `'dlm_expiration_format'` option to the "License Manager -> Settings -> General" page with a link to the [WordPress documentation on date and time formatting](https://wordpress.org/support/article/formatting-date-and-time/) and let users set the entire format.

An extra nice feature would be to allow the user to specify the current WordPress date and time formats using merge codes like `{{DATE_FORMAT}}, {{TIME_FORMAT}} T`.

## PR

If this sounds good, I would be happy to submit a pull request with either solution.

**Comment by gdarko** [comment]
Hi @pondermatic,

Thanks for pointing out the issue.

The solution 2 sounds better to me, feel free to submit pr. I will be reviewing those shortly after.

Best Regards,
Darko
