### ISSUE TITLE
Generator with expiry date doesnt seem to propagate to sold licenses

### ISSUE THREAD

**Issue by EmilDohne** [gdarko/digital-license-manager#44]
Hey, I wanted to thank you for this great tool! I however ran across something which im unsure of.

I have a generator for a trial version which has a 14 day expiry period which is attached to an item on woocommerce to automatically generate licenses. However, when these licenses are generated they are set to expire at "Never".

From what I can tell this isnt something explicit to the pro version and is perhaps a bug? This is on version 1.6.1.

**Comment by gdarko** [comment]
Hey @EmilDohne  - This is indeed a bug. Thanks for reporting it. It will be fixed in the upcoming 1.6.2 version.

**Comment by EmilDohne** [comment]
Hi @gdarko thanks for looking into it so quickly. I will be looking forward to it!

**Comment by EmilDohne** [comment]
Didnt have time to test until yet but this does appear to be fixed so im going to close the issue, thanks for looking into it :)
