### ISSUE TITLE
Show product variation info on the Checkout and on Orders page

### ISSUE THREAD

**Issue by kovacsv** [gdarko/digital-license-manager#45]
Hi, first of all thank you for this great product. I'm using it successfully, but it would be wonderful if it could show the variation details of licenses after a checkout.

For example I have "My cool product" with two different variations. If I order two variations it's indistinguishable which license key is associated to which variation.

![image](https://github.com/gdarko/digital-license-manager/assets/2034315/64e2b11d-c0ea-47c8-9e95-114985e422e0)

**Comment by gdarko** [comment]
Hey @kovacsv  - 

This seems to work already.

![image](https://github.com/user-attachments/assets/e8604e6a-a3eb-429d-a7e7-fa561bcde018)

Feel free to reopen if this issue still exists.

Best Regards,
DG
