### ISSUE TITLE
Can't activate licenses with special characters

### ISSUE THREAD

**Issue by purriexyz** [gdarko/digital-license-manager#47]
Hi,

I've imported some older license keys I created before. But upon activation these fails with notification of "No route was found matching the URL and request method."

If I try directly with the web browser it just gives a 404 error. 

Keys without special chars seem to work just fine. For instance key that does not work: c$CNBmRp%6@qgM7FynD#

**Comment by gdarko** [comment]
Hey @purriexyz  - Are you using the API for this? If so i think i have an easy solution for you. Let me know.

**Comment by purriexyz** [comment]
Hey @gdarko 

Yes I am using the API to activate the license. I tried via a direct call to the API via CuRL but the DLM-PHP class didn't work either.

**Comment by gdarko** [comment]
Hey @purriexyz -

Sometime ago we introduced a way to pass "Complex" license keys (like in your keys)

https://docs.codeverve.com/digital-license-manager/rest-api/complex-licenses/

All you need is to hash your key using the Digital License Manager secret keys and pass the license as `hashed-**the-hash**`

Best Regards,
Darko

**Comment by purriexyz** [comment]
Thanks that indeed works. However if you enter a wrong license key it will give the error (probably not the exact error) that license key hashed-xxxxxxx has not been found.

Is it maybe possible to return the unhashed key in that error?

**Comment by gdarko** [comment]
Hey @purriexyz  - The message has been updated to generic one.

**Comment by gdarko** [comment]
Closing as complete
