### ISSUE TITLE
AbstractResourceRepository::delete() prepare

### ISSUE THREAD

**Issue by pondermatic** [gdarko/digital-license-manager#7]
[`AbstractResourceRepository::delete()`](https://github.com/gdarko/digital-license-manager/blob/1.3.3/includes/Abstracts/AbstractResourceRepository.php#L382) calls `$wpdb->prepare()` with an already prepared query, via [`AbstractResourceRepository::sqlINValues()`](https://github.com/gdarko/digital-license-manager/blob/1.3.3/includes/Abstracts/AbstractResourceRepository.php#L589) and no placeholders. This causes [`wpdb::prepare()`](https://github.com/WordPress/WordPress/blob/6.0.2/wp-includes/wp-db.php#L1401) to log a "doing it wrong" warning.

I can think of two different solutions to fix this issue.
1. replace
   ```php
   $sqlQuery = $wpdb->prepare( "DELETE FROM {$this->table} WHERE {$this->primaryKey} IN (" . $ids . ")" );
   ```
   with
   ```php
   $sqlQuery = "DELETE FROM {$this->table} WHERE {$this->primaryKey} IN ($ids)";
   ```
2. replace
    ```php
    $ids      = implode( ',', array_map( array( $this, 'sqlINValues' ), $ids ) );
    $sqlQuery = $wpdb->prepare( "DELETE FROM {$this->table} WHERE {$this->primaryKey} IN (" . $ids . ")" );
    ```
    with
    ```php
    $sqlQuery = $wpdb->prepare(
    	"DELETE FROM {$this->table} WHERE {$this->primaryKey} IN ($placeholders)",
    	$ids
    );
    ```

If this were not a WordPress plugin, I would choose solution 1, but since WordPress strongly encourages using [core APIs](https://make.wordpress.org/core/handbook/best-practices/core-apis/), solution 2 is recommended.

@gdarko, let me know if you want me to submit a pull request to fix this issue.

**Comment by gdarko** [comment]
@pondermatic  - Thanks for reporting the issue. I think 2. will be great. Feel free to submit pr.
